name = "shopmon"
main = "worker.api.js"
workers_dev = false
compatibility_date = "2022-03-04"
account_id = "963ff7fb9c523564b5f3a398ab39d488"
routes = ["shopmon.fos.gg/api/*"]

minify = true
node_compat = false

[vars]
MAIL_FROM="Shopmon <shopmon@fos.gg>"
FRONTEND_URL="https://shopmon.fos.gg"

[build]
command = "node_modules/.bin/esbuild --bundle --outfile=worker.api.js --format=esm --conditions=node --minify --sourcemap src/workers/api.ts --source-root=/"

[durable_objects]
bindings = [{name = "SHOPS_SCRAPE", class_name = "ShopScrape"}, {name = "PAGESPEED_SCRAPE", class_name = "PagespeedScrape"}]

[[migrations]]
tag = "v1"
new_classes = ["ShopScrape"]

[[migrations]]
tag = "v2"
new_classes = ["PagespeedScrape"]

[[kv_namespaces]]
  binding = "kvStorage"
  id = "61a260743f17482e92fa5cb2c340edec"
  preview_id = "61a260743f17482e92fa5cb2c340edec"