name: API Deploy

on:
  push:
    branches: [ main ]
    paths:
      - api/**
  workflow_dispatch:
jobs:
  api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: NPM Install
      run: |
        cd api
        npm install
    - name: Publish API
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        workingDirectory: 'api'
        command: '-c api.toml publish'
    - name: Publish Cron Shop Update
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        workingDirectory: 'api'
        command: '-c cron-shop-update.toml publish'
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: production
        sourcemaps: './api/'